/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:eb92afb40d3354ec762ba06058f8f554:648b274c0e3dc18333ddf18c584eac01:661758968771fee6b10c7ca7a9054a93$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class android_packed
	{
		public const string Sprites_android1 = "sprites/android1";
		public const string Sprites_android2 = "sprites/android2";
		public const string Sprites_android3 = "sprites/android3";
		public const string Sprites_android4 = "sprites/android4";
	}
}