/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:fae0a79da30309615785c8957030609a:f1d706da3934e9cf5dc5f4c61a33f6bc:7de42156f25b693bd0d7ccd72987ff69$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class entities
	{
		public const string Android1 = "android1";
		public const string Android2 = "android2";
		public const string Android3 = "android3";
		public const string Android4 = "android4";
		public const string C = "c";
		public const string Cpp = "cpp";
		public const string Csharp = "csharp";
		public const string Java = "java";
		public const string Mss000 = "mss000";
		public const string Mss001 = "mss001";
		public const string Mss010 = "mss010";
		public const string Mss011 = "mss011";
		public const string Mss100 = "mss100";
		public const string Mss101 = "mss101";
		public const string Mss110 = "mss110";
		public const string Mss111 = "mss111";
		public const string Powerup_CPU = "powerup_CPU";
		public const string Powerup_kaffee = "powerup_kaffee";
		public const string Powerup_usb = "powerup_usb";
	}
}