/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:92c47824e0fd9c12ec2c82d237374cff:35f5130712fc28f1bcb02640ec14e9da:7de42156f25b693bd0d7ccd72987ff69$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class entities
	{
		public const string Android1 = "android1";
		public const string Android2 = "android2";
		public const string Android3 = "android3";
		public const string Android4 = "android4";
		public const string C = "c";
		public const string Cpp = "cpp";
		public const string Csharp = "csharp";
		public const string Java = "java";
		public const string Mss000 = "mss000";
		public const string Mss001 = "mss001";
		public const string Mss010 = "mss010";
		public const string Mss011 = "mss011";
		public const string Mss100 = "mss100";
		public const string Mss101 = "mss101";
		public const string Mss110 = "mss110";
		public const string Mss111 = "mss111";
		public const string Powerup_kaffee = "powerup_kaffee";
	}
}