/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:0ede3ba3d63c93799c78018c410a8904:19268b7b30c1d666b5c71ff4df78f8a1:a752404cb359b1fa636cef9fa50b1723$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class gui
	{
		public const string C = "c";
		public const string Cpp = "cpp";
		public const string Heart_full = "heart_full";
		public const string Heart_half = "heart_half";
		public const string Java = "java";
		public const string Maschinensprache = "maschinensprache";
	}
}