/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:f50996921713bb5401a6b6630aa63ead:54b12e1a0199789d9076d63e5cf48831:a752404cb359b1fa636cef9fa50b1723$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class gui
	{
		public const string C = "c";
		public const string Cpp = "cpp";
		public const string Csharp = "csharp";
		public const string Heart_full = "heart_full";
		public const string Heart_half = "heart_half";
		public const string Java = "java";
		public const string Maschinensprache = "maschinensprache";
	}
}