/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:a7bbd06f270b44ce4b9634533f6054ef:50a3500cd8a90e0f7dac3f7e2ae04234:a752404cb359b1fa636cef9fa50b1723$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class gui
	{
		public const string C = "c";
		public const string Cpp = "cpp";
		public const string Csharp = "csharp";
		public const string Heart_full = "heart_full";
		public const string Heart_half = "heart_half";
		public const string Java = "java";
		public const string Maschinensprache = "maschinensprache";
	}
}