/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:5d92bdb45919d3aeb2529dccddc65238:c5f0a574562ef86d1d4f2262f888b46a:7edb553f07abd4d7247497c914f7282c$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class weapons
	{
		public const string C = "c";
		public const string Cpp = "cpp";
		public const string Java = "java";
		public const string Maschinensprache = "maschinensprache";
	}
}