/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:86f47f35209805ef80477b631d67e8ee:16cca9cccfece36685257879def2bca5:7edb553f07abd4d7247497c914f7282c$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class weapons
	{
		public const string C = "c";
		public const string Cpp = "cpp";
	}
}