/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:da69f5c6a69dee8da327746c479602b6:99bc4d47885f3dab0b1b4ab428ed67d7:7008ad4d447f9ad8ca314be36d061462$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class effect_packed
	{
		public const string Poof_001 = "poof_001";
		public const string Poof_002 = "poof_002";
		public const string Poof_003 = "poof_003";
		public const string Poof_004 = "poof_004";
		public const string Poof_005 = "poof_005";
		public const string Poof_006 = "poof_006";
		public const string Poof_007 = "poof_007";
	}
}