/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:367deb605432e2139b77c7b9ea7b5714:2414eb980e990b6ec96cf028ef17dfd9:7de42156f25b693bd0d7ccd72987ff69$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class entities
	{
		public const string Android1 = "android1";
		public const string Android2 = "android2";
		public const string Android3 = "android3";
		public const string Android4 = "android4";
		public const string C = "c";
		public const string Cpp = "cpp";
		public const string Csharp = "csharp";
		public const string Idle_000 = "idle_000";
		public const string Idle_001 = "idle_001";
		public const string Idle_002 = "idle_002";
		public const string Idle_003 = "idle_003";
		public const string Idle_004 = "idle_004";
		public const string Idle_005 = "idle_005";
		public const string Idle_006 = "idle_006";
		public const string Idle_007 = "idle_007";
		public const string Idle_008 = "idle_008";
		public const string Idle_009 = "idle_009";
		public const string Idle_010 = "idle_010";
		public const string Idle_011 = "idle_011";
		public const string Java = "java";
		public const string Mss000 = "mss000";
		public const string Mss001 = "mss001";
		public const string Mss010 = "mss010";
		public const string Mss011 = "mss011";
		public const string Mss100 = "mss100";
		public const string Mss101 = "mss101";
		public const string Mss110 = "mss110";
		public const string Mss111 = "mss111";
		public const string Powerup_CPU = "powerup_CPU";
		public const string Powerup_kaffee = "powerup_kaffee";
		public const string Powerup_Monitor = "powerup_Monitor";
		public const string Powerup_usb = "powerup_usb";
		public const string RunRight_000 = "runRight_000";
		public const string RunRight_001 = "runRight_001";
		public const string RunRight_002 = "runRight_002";
		public const string RunRight_003 = "runRight_003";
		public const string RunRight_004 = "runRight_004";
		public const string RunRight_005 = "runRight_005";
		public const string RunRight_006 = "runRight_006";
		public const string RunRight_007 = "runRight_007";
		public const string Windows1 = "windows1";
		public const string Windows2 = "windows2";
		public const string Windows3 = "windows3";
		public const string Windows4 = "windows4";
		public const string WindowsVista_1 = "WindowsVista_1";
		public const string WindowsVista_2 = "WindowsVista_2";
		public const string WindowsVista_3 = "WindowsVista_3";
		public const string WindowsVista_4 = "WindowsVista_4";
	}
}