/*
 * Class auto generated by TexturePacker
 *
 * Contains references to each image within the sprite sheet.
 *
 * https://www.codeandweb.com/texturepacker
 * $TexturePacker:SmartUpdate:7d936a0218dc1d55c4f447936022fa0a:b7e230ee5b3322749ddec7200111337c:7edb553f07abd4d7247497c914f7282c$
 *
 */
namespace TexturePackerMonoGameDefinitions
{
	public class weapons
	{
		public const string C = "c";
		public const string Cpp = "cpp";
		public const string Csharp = "csharp";
		public const string Java = "java";
		public const string Mss000 = "mss000";
		public const string Mss001 = "mss001";
		public const string Mss010 = "mss010";
		public const string Mss011 = "mss011";
		public const string Mss100 = "mss100";
		public const string Mss101 = "mss101";
		public const string Mss110 = "mss110";
		public const string Mss111 = "mss111";
	}
}